### PR TITLE
Building with responsive design code review request.

### PR DESCRIPTION
**Pull request by Meltrust**
# In this project we:

- Built a clone from "The Next Web" webpage using _HTML_ and _CSS_.

- Added media queries with 2 breakpoints in order to make the page usable in devices of all sizes.

- Replicated the website putting emphasis on how it behaves differently depending on the size of the screen where the website is rendered.

- Aligned all elements with _CSS flex and grid_.

- Used various techniques such as _CSS gradients_.

- Built a descriptive readme for the project.

- Issued a descriptive pull request.

### CODE REVIEW

**Comment by sumancrest0001** [comment]
**STATUS: CHANGES REQUIRED
Awesome work TEAM :clap: :clap: :satisfied: :satisfied:**

The project looks amazing and similar to that of the original one at all breakpoints. But there are a couple of minor issues that need to be fixed to get :+1: :+1:  from our side. 

Kindly make the following changes and submit the project for another review.

[REQUIRED] Hamburger menu is missing on a small and medium screen. We have to add that on the right side.
In your project
Screenshot from 2020-04-11 11-43-46

in the original site
Screenshot from 2020-04-11 11-44-20

**Comment by sumancrest0001** [comment]
[REQUIRED] There is an overlap between two sections on the medium screen. Please fix this issue.

on your project.
Screenshot from 2020-04-11 11-40-06

on the original site
Screenshot from 2020-04-11 11-57-20

**Comment by sumancrest0001** [comment]
[Optional] Please remove the gradient background on medium and small screens as in the original site.
In your project :point_down: 
Screenshot from 2020-04-11 11-44-42

It should be like this :point_down: 
Screenshot from 2020-04-11 11-44-29

**Comment by sumancrest0001** [comment]
[Optional] Please try to emulate a similar layout as that of the original one. Have a look.
Add red dots on each unordered list item. Increase the font-weight of the title(Gear).
**in your project.**
Screenshot from 2020-04-11 11-45-06


It should be :point_down:  :point_down: 

Screenshot from 2020-04-11 12-05-44

**Comment by sumancrest0001** [comment]
**It is not mandatory to fix optional changes.** 
All the best with another review.

**Comment by Meltrust** [comment]
## Thanks for the review.  

I made all the required and optional changes.  I also made some tweaks to the whole project so it looks cooler (like in the original site lots of hovers, transitions, and animations, including the main logo) and fixed some incompatibilities with Chrome.  

**_Requesting another code review._**

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :100: :1st_place_medal: :100: 

Hi @SmithVyne and @Meltrust :smile: :smile: 

Congrats on the hard work. You guys did also the optional changes and your project looks beautiful and professional :+1: :muscle: :fireworks: 

### **So, your project was approved** :fireworks: :fireworks:  :fireworks:  :fireworks: 




If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next project** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Comment by SmithVyne** [comment]
Thank you Vieira fro your code review.
It was great working on this project

**Pull request merged**
